export interface Weather {
  id: string,
  celsiusTemp: number,
  fahrenheitTemp: number,
  celsiusFeelsLike: number,
  fahrenheitFeelsLike: number,
  pressureInMmhg: number,
  date: string,
  time: string,
  weatherDescription: string,
  windSpeed: string,
  windDeg: number,
  sunrise: string,
  sunset: string,
  cod: string,
}