export interface Result {
  id: string,
  name: string,
  country: string,
  temp: number,
  feelLike: number,
  pressure: number,
  date: number,
  time: number,
  weatherDescription: string,
  windSpeed: string,
  windDeg: number,
  sunrise: number,
  sunset: number,
  cod: string,
}